feat: Auto-generate storybook screenshots

diff --git a/scripts/generate-stories-screenshots b/scripts/generate-stories-screenshots
--- a/scripts/generate-stories-screenshots
+++ b/scripts/generate-stories-screenshots
@@ -4,9 +4,14 @@ set -e -u
 
 if [ -z ${1+x} ]; then
   echo "Missing argument 1: storybook port"
-  exit 127
+  exit 1
+elif [ -z ${2+x} ]; then
+  echo "Missing argument 2: screenshots_dir"
+  exit 1
 fi
 
-STORYBOOK_PORT=$1
+storybook_port="$1"
+screenshots_destination="$2"
 
-storybook-chrome-screenshot -p ${STORYBOOK_PORT} -c .storybook
+rm -Rf ${screenshots_destination}/*
+storybook-chrome-screenshot -p "${storybook_port}" -c ".storybook" -o "${screenshots_destination}"
